[package]
name = "directwrite"
version = "0.0.8"
authors = ["Conni Hilarides <connorcpu@live.com>"]
description = """
A safe abstraction for interacting with DirectWrite, intended initially
to be used with direct2d for easy text rendering.
"""
repository = "https://github.com/Connicpu/directwrite-rs"
documentation = "https://docs.rs/directwrite/*/x86_64-pc-windows-msvc/directwrite/"
license = "MIT/Apache-2.0"

[dependencies]
uuid = "0.4"

[dependencies.winapi]
version = "0.3"
features = ["dwrite", "winbase", "libloaderapi", "errhandlingapi"]

