[package]
name = "directwrite"
version = "0.0.7"
authors = ["Conni Hilarides <connorcpu@live.com>"]
description = """
A safe abstraction for interacting with DirectWrite, intended initially
to be used with direct2d for easy text rendering.
"""
repository = "https://github.com/Connicpu/directwrite-rs"
documentation = "https://docs.rs/directwrite/*/x86_64-pc-windows-msvc/directwrite/"
license = "MIT/Apache-2.0"

[dependencies]
uuid = "0.4"

# Eventually: Use 0.3 when it's pushed to crates.io
[dependencies.winapi]
git = "https://github.com/retep998/winapi-rs.git"
branch = "dev"
features = ["dwrite", "winbase", "libloaderapi", "errhandlingapi"]

