[package]
name = "directwrite"
version = "0.1.0"
authors = ["Connie Hilarides <conni_h@outlook.com>"]
description = """
A safe abstraction for interacting with DirectWrite, intended initially
to be used with direct2d for easy text rendering.
"""
repository = "https://github.com/Connicpu/directwrite-rs"
documentation = "https://docs.rs/directwrite/*/x86_64-pc-windows-msvc/directwrite/"
license = "MIT/Apache-2.0"

[target.'cfg(windows)'.dependencies]
wio = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["dwrite", "winbase"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

