[package]
name = "directwrite"
version = "0.0.1"
authors = ["Connor Hilarides <connorcpu@live.com>"]
description = """
A safe abstraction for interacting with DirectWrite, intended initially
to be used with direct2d for easy text rendering.
"""
repository = "https://github.com/Connorcpu/direct2d-rs"
license = "MIT"

[dependencies]
winapi = "*"
uuid = "0.1"
kernel32-sys = "0.2"
user32-sys = "0.1"
